#ifndef UTILS_H
#define UTILS_H


enum MessageType {
    MESSAGE_UNKNOWN = 0,
    MESSAGE_NEW_DEIVCE_CONNECT = 1,
    MESSAGE_LOGIN = 2,
    MESSAGE_LOGIN_RST = 3,
    MESSAGE_UPDATE_ACCOUNT = 4,
    MESSAGE_UPDATE_ACCOUNT_RST = 5,
    MESSAGE_ADD_ACCOUNT = 6,
    MESSAGE_ADD_ACCOUNT_RST = 7,
    MESSAGE_DELETE_ACCOUNT = 8,
    MESSAGE_DELETE_ACCOUNT_RST = 9,
    MESSAGE_ALL_ACCOUNTS_INFO = 10,
    MESSAGE_ALL_MAPS_INFO = 11,
    MESSAGE_SET_MAP_INIT_POSE = 12,
    MESSAGE_SET_MAP_INIT_POSE_RST = 13,
    MESSAGE_CURRENT_MAP_AND_TASKS = 14,
    MESSAGE_CURRENT_MAP_AND_TASKS_RST = 15,
    MESSAGE_TASKS_INFO = 16,
    MESSAGE_SET_TASKS = 17,
    MESSAGE_SET_TASKS_RST = 18,
    MESSAGE_CURRENT_MAP_AND_TASK = 19,
    MESSAGE_CURRENT_MAP_AND_TASK_RST = 20,
    MESSAGE_TASK_INFO = 21,
    MESSAGE_LOCALIZATION_INFO = 22,
    MESSAGE_CHASSIS_INFO = 23,
    MESSAGE_PERCEPTION_OBSTACLES = 24,
    MESSAGE_PLANNING_COMMAND_PATH = 25
};

enum PermissionLevel {
  PERMISSION_UNKONWN = 0,
  PERMISSION_NORMAL = 1,
  PERMISSION_ADMIN = 2,
  PERMISSION_ROOT = 3
};

#endif // UTILS_H
